### ISSUE TITLE
Fails on python-3.6: 'ascii' codec can't decode byte 0xc3 in position 63

### ISSUE THREAD

**Issue by yurivict** [hickeroar/simplebayes#3]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 11, in <module>
    long_description = open('README.rst', 'r').read(),
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 63: ordinal not in range(128)
```

**Comment by hickeroar** [comment]
Can you provide a text sample that gave you this result? Just want to make sure I can properly reproduce it. Sorry for the much delayed response.

**Comment by yurivict** [comment]
I can't reproduce it now.
